services:
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Exambyte
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=iamgroot
