logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:postgresql://database:5432/Exambyte
    username: user
    password: iamgroot
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
